### ISSUE TITLE
Container Statistics

### ISSUE THREAD

**Issue by mjdavies** [infinityworks/docker-cloud-exporter#1]
Hi Rucknar

This looks really good mate, but was wondering if it's going to be good enough to replace something like this?

https://github.com/vegasbrianc/prometheus

We're using docker-cloud so I can't just spin up Brians compose file on the node, unfortunately.

Does your exporter show container metrics?  Or is that something not in scope here, or something I could add?

Speak soon

Matt

**Comment by Rucknar** [comment]
Hey Matt,

This service is explicitly to expose a prometheus metrics interface, it's not a pre-configured monitoring system as the one you listed. Just having a look at the above though, it wouldn't be difficult to get that running on-top of docker-cloud at all. The exporter in this repo would be a valid scrape target for the Prometheus that sits inside that system.

Happy to jump on a call to talk through the important bits if you fancy.

With regards to the container metrics, that would be something cadvisor (used in the link you provided) would offer. The docker-cloud API has the potential to display some container information, but not enough for real-world service monitoring.

**Comment by mjdavies** [comment]
Thanks for getting back

I think I was being a bit thick with Brians prometheus setup, I can get it running by adding some config files into the node filesystem, doh!!

Thanks anyway though.
